output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_name" {
  description = "EKS cluster Name."
  value       = module.eks.cluster_name
}

output "cluster_endpoint" {
  description = "Endpoint for cluster control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_arn" {
  description = "arn of cluster control plane."
  value       = module.eks.cluster_arn
}

output "cluster_iam_role_name" {
  description = "IAM role name attached to the cluster control plane."
  value       = module.eks.cluster_iam_role_name
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "cluster_primary_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_primary_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = local.kubeconfig
}

# output "config_map_aws_auth" {
#   description = "A kubernetes configuration to authenticate to this EKS cluster."
#   value       = module.eks.aws_auth_configmap_yaml
# }

output "oidc_provider" {
  description = "A kubernetes OIDC Provide."
  value       = module.eks.oidc_provider
}

output "oidc_provider_arn" {
  description = "A kubernetes OIDC Provide ARN."
  value       = module.eks.oidc_provider_arn
}

output "eks_managed_node_groups_autoscaling_group_names" {
  description = "EKS Managed Node Groups"
  value       = module.eks.eks_managed_node_groups_autoscaling_group_names
}

output "self_managed_node_groups_autoscaling_group_names" {
  description = "Self Managed Node Groups"
  value       = module.eks.self_managed_node_groups_autoscaling_group_names
}
